version: "3"

services:
  atlas:
    build:
      context: ./backend
      dockerfile: backend-dev.dockerfile
    entrypoint: /opt/scaife-stack/src/entrypoint-dev.sh
    command: python manage.py runserver 0.0.0.0:8000
  viewer:
    build:
      context: ./frontend
      dockerfile: frontend-dev.dockerfile
    command: /bin/sh -c 'yarn install && yarn serve'
