version: "3"

services:
  atlas:
    volumes:
      - ./backend:/opt/scaife-stack/src
      - db-data:/opt/scaife-stack/db-data
    ports:
      - "8000:8000"
    environment:
      DB_DATA_PATH: /opt/scaife-stack/db-data
  viewer:
      volumes:
          - ./frontend:/app
          - node-modules:/app/node_modules
      working_dir: /app
      ports:
          - "8080:8080"
      environment:
        VUE_APP_ATLAS_GRAPHQL_ENDPOINT: "http://localhost:8000/graphql/"

volumes:
    db-data:
    node-modules:
